package co.taggar.notifications

internal object Constants {
    const val NOTIFICATION_TYPE = "ANDP"
    const val TEMPLATE_LARGE = "LARGE"
    const val TEMPLATE_CONVERSATION = "CONVERSATION"
    const val TEMPLATE_BIG_TEXT = "BIG_TEXT"
    const val TEMPLATE_INBOX = "INBOX"
    const val DATA_TYPE = "type"
    const val DATA_ID = "id"
    const val DATA_TITLE = "title"
    const val DATA_MESSAGE = "message"
    const val DATA_COLOR = "color"
    const val DATA_DEEPLINK = "deeplink"
    const val DATA_TEMPLATE = "template"
    const val DATA_IMAGE = "image"
    const val DATA_CONVERSATION = "conversation"
    const val DATA_LINES = "lines"
    const val DATA_BUTTONS = "buttons"
    const val JSON_TEXT = "text"
    const val JSON_TIMESTAMP = "timestamp"
    const val JSON_SENDER = "sender"
    const val CHANNEL_ID = "default_channel_id"
    const val CHANNEL_NAME = "General"
}
